console.log("hello world");
var myNumber = 10;
console.log(typeof (myNumber));
console.log(myNumber);
var myString = "abc";
console.log(typeof (myString));
console.log(myString);
var myAny = "universal";
console.log(typeof (myAny));
console.log(myAny);
var myArr = [];
myArr.push(1);
myArr.push(2);
myArr.push(3);
console.log(myArr);
